# docker-compose build
version: '2.1'
networks:
  ohsome:
    name: ohsome

services:
  ohsome-api:
    image: julianpsotta/ohsome-api:1.3.2
    container_name: ohsome-api
    environment:
      DATA_FILE: "heidelberg_68900_2020-07-23.oshdb.mv.db"
    volumes:
      - ./data:/opt/app/data
    ports:
      - 8080:8080
    restart: always
    networks:
      - ohsome
#    volumes:
#      - .:/app
