name: Publish Docker image
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install and run pre-commit
        uses: pre-commit/action@v2.0.0
        with:
          extra_args: --all-files
  push_to_registries:
    needs:
      - lint
    name: Push Docker image to docker hub and github packages
    runs-on: ubuntu-latest
    steps:
      - name: Download fallback file
        run: |
          curl -o fallback.oshdb.mv.db http://downloads.ohsome.org/v0.6/europe/germany/baden-wuerttemberg/heidelberg_68900_2020-07-23.oshdb.mv.db
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          # list of Docker images to use as base name for tags
          images: |
            julianpsotta/ohsome-api
      #            ${{ github.repository }}/ohsome-api
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Prepare
        id: prepare
        run: |
          DOCKER_IMAGE=julianpsotta/ohsome-api
          DOCKER_VERSION=latest
          echo ::set-output name=docker_image::${DOCKER_IMAGE}
          echo ::set-output name=docker_version::${DOCKER_VERSION}

      - name: Login to DockerHub
        #        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      #      - name: Login to GHCR
      #        if: github.event_name != 'pull_request'
      #        uses: docker/login-action@v1
      #        with:
      #          registry: ghcr.io
      #          username: ${{ github.repository_owner }}
      #          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push latest version
        uses: docker/build-push-action@v2
        with:
          context: .
          # push: ${{ github.event_name != 'pull_request' }}
          push: true
          tags: ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.docker_version }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            FALLBACK_DATA_FILE=./fallback.oshdb.mv.db
            OHSOMEAPI_VERSION=latest
