# This is a basic workflow to help you get started with Actions

name: Testing

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ "**" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install and run pre-commit
        uses: pre-commit/action@v2.0.0
        with:
          extra_args: --all-files
  test_docker_build:
    needs:
      - lint
    name: Build docker image latest for testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Prepare
        id: prepare
        run: |
          DOCKER_IMAGE=julianpsotta/ohsome-api
          DOCKER_PLATFORMS=linux/amd64

          TAGS_LATEST="--tag ${DOCKER_IMAGE}:latest"

          curl -o fallback.oshdb.mv.db http://downloads.ohsome.org/v0.6/europe/germany/baden-wuerttemberg/heidelberg_68900_2020-07-23.oshdb.mv.db

          echo ::set-output name=buildx_args_latest::--platform ${DOCKER_PLATFORMS} \
                      --build-arg OHSOMEAPI_VERSION=latest \
                      --build-arg FALLBACK_DATA_FILE=fallback.oshdb.mv.db \
                      ${TAGS_LATEST} .
      - name: Build latest for testing
        run: |
          docker buildx build --output "type=image,push=false" ${{ steps.prepare.outputs.buildx_args_latest }}
